#!/usr/bin/env python3
#
# Copyright (c) 2022 Pim van Pelt
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -*- coding: utf-8 -*-

import sys
import yaml
import logging
from validator import Validator
from vpp.vppapi import VPPApi

try:
    import argparse
except ImportError:
    print("ERROR: install argparse manually: sudo pip install argparse")
    sys.exit(-2)


def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('-c', '--config', dest='config', required=True, type=str, help="""YAML configuration file for VPP""")
    parser.add_argument('-s', '--schema', dest='schema', type=str, default='./schema.yaml', help="""YAML schema validation file""")
    parser.add_argument('-d', '--debug', dest='debug', action='store_true', help="""Enable debug, default False""")
    parser.add_argument('-q', '--quiet', dest='quiet', action='store_true', help="""Be quiet (only log warnings/errors), default False""")

    args = parser.parse_args()

    level = logging.INFO
    if args.debug:
        level = logging.DEBUG
    if args.quiet:
        level = logging.WARNING
    logging.basicConfig(format='[%(levelname)-8s] %(name)s.%(funcName)s: %(message)s', level=level)

    try:
        with open(args.config, "r") as f:
            logging.info("Loading configfile %s" % args.config)
            cfg = yaml.load(f, Loader = yaml.FullLoader)
            logging.debug("Config: %s" % cfg)
    except:
        logging.error("Couldn't read config from %s" % args.config)
        sys.exit(-1)

    validator = Validator(schema=args.schema)
    if not validator.valid_config(cfg):
        logging.error("Configuration is not valid, bailing")
        sys.exit(-2)

    config_phys = validator.get_phys(cfg)
    vpp = VPPApi()
    vpp.readconfig()
    if not vpp.phys_exist(config_phys):
        logging.error("Not all PHYs in the config exist in VPP")
        vpp.disconnect()
        sys.exit(-3)

    vpp.dump()

    vpp.disconnect()

if __name__ == "__main__":
    main()
